FROM continuumio/miniconda3
# FROM travisci/ci-sardonyx
# FROM ubuntu
# RUN apt-get update
# RUN apt-get upgrade
# RUN apt-get install wget -y
# RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
# ENV PATH="~/miniconda/bin:${PATH}"
# RUN echo $PATH
# RUN bash miniconda.sh -b -p $HOME/miniconda
# RUN ~/miniconda/bin/conda list
# RUN hash -r
# RUN ~/miniconda/bin/conda config --set always_yes yes --set changeps1 no
# RUN ~/miniconda/bin/conda update -q conda
# RUN ~/miniconda/bin/conda info -a
# RUN ~/miniconda/bin/conda install pip
# RUN ~/miniconda/bin/conda install cython
# RUN apt-get install git -y
# RUN apt-get install inetutils-ping -y
# RUN git clone --branch dev https://github.com/fastlmm/FaST-LMM.git fastlmm
# WORKDIR /fastlmm
# RUN ~/miniconda/bin/pip install virtualenv
# ENV PYTHONPATH=/fastlmm
# RUN ~/miniconda/bin/conda install --file conda_requirements.txt
# RUN ~/miniconda/bin/conda install  psutil
# RUN apt-get install build-essential -y
# RUN apt-get install gcc-multilib -y
# #RUN apt-get install libomp-dev -y
# RUN ~/miniconda/bin/pip install -r requirements.txt
# RUN ~/miniconda/bin/virtualenv fresh


# # ENV PATH="${PATH}:/opt/python/cp37-cp37m/bin:/opt/rh/devtoolset-8/root/usr/bin"
# # RUN curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.rpm.sh | bash
# # RUN yum install git-lfs -y
# # RUN git clone --branch dev https://github.com/fastlmm/PySnpTools.git pysnptools
# # WORKDIR /pysnptools
# # RUN git lfs install
# # RUN git lfs fetch
# # RUN git lfs checkout
# # RUN pip install cython
# # RUN pip install virtualenv
# # ENV PYTHONPATH="/pysnptools"
# # RUN pip install -r requirements.txt
# # RUN virtualenv fresh