name: CI
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
    
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, windows-2022, ubuntu-latest]
        python-version: [3.9, "3.10", "3.11", "3.12"]
        arch: [x86_64, arm64]
        include:
          - os: macos-13
            arch: x86_64
          - os: macos-14
            arch: arm64
          - os: windows-2022
            arch: x86_64
          - os: ubuntu-latest
            arch: x86_64
            build: "manylinux2014"
          - os: ubuntu-latest
            arch: arm64
            build: "manylinux2014"
          - os: ubuntu-latest
            arch: x86_64

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Miniconda ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
    - name: Install Project
      shell: bash -l {0}
      run: |
        conda install numpy
        pip freeze
        pip install .
        python setup.py sdist

    - name: Test
      shell: bash -l {0}
      run: |
        pip uninstall fastlmm --yes
        export PYTHONPATH=${GITHUB_WORKSPACE}
        cd tests
        python test.py

    - name: Save SDist
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9'
      uses: actions/upload-artifact@v3
      with:
        name: sdist
        path: dist/*.tar.gz
